language: python
python:
  - "3.9"

before_script:
  - app/emsdk/emsdk install latest
  - app/emsdk/emsdk activate latest

script:
  - source app/emsdk/emsdk_env.sh
  - mkdir web/app
  - emcc -s EXPORTED_FUNCTIONS=_main,_app_build,_app_reset,_app_start,_app_video \
         -s WASM=1 -s USE_SDL=2 -I app/lua app/pixweb.c -o web/app/pixtoy.js

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: web
  keep_history: false
  on:
    branch: master
