language: python
python:
  - "3.9"

before_script:
  - app/emsdk/emsdk install latest
  - app/emsdk/emsdk activate latest

script:
  - source app/emsdk/emsdk_env.sh
  - emcc -s WASM=1 -s USE_SDL=2 -I ../app/lua ../app/pixapp.c -o web/pixtoy.js

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: web
  keep_history: false
  on:
    branch: master
