#!/usr/bin/env bash

if [ ! -d "web/app" ];
    then mkdir "web/app";
fi

if [ "$1" = "clean" ]; then
    echo "cleaning build..."
    if [ -d "web/app" ]; then
        rm -rf "web/app"
    fi
fi

if [ "$1" = "server" ]; then
    echo "starting server..."
    pushd "web"
    python3 -m http.server &
    popd
fi

if [ "$1" = "setup" ]; then
    echo "setting up emsdk..."
    ./app/emsdk/emsdk install latest
    ./app/emsdk/emsdk activate latest
    chmod 755 ./app/emsdk/emsdk_env.sh
    source ./app/emsdk/emsdk_env.sh
fi

if [ -z "$1" ]; then
    echo "building application..."
    emcc -s EXPORTED_FUNCTIONS=_main,_app_build,_app_start,_app_video -s WASM=1 -s USE_SDL=2 -I app/lua app/pixweb.c -o web/app/pixtoy.js
fi

echo "complete!"
